[package]
name = "vishvakarman"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
serde = { version = "1.0", features = ["derive"] }
clap = { version = "3.0", features = ["derive"] }
chrono = "*"
eyre = "0.6.8"
